name: Release Workflow

on:
  release:
    types: [created]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        target:
          - os: linux
            arch: "amd64"
          - os: linux
            arch: "arm64"
          - os: darwin
            arch: "amd64"
          - os: darwin
            arch: "arm64"
          - os: windows
            arch: "386"
          - os: windows
            arch: "amd64"

    name: Build and publish package
    steps:
      - uses: actions/checkout@v2

      - name: Install dependencies
        uses: actions/setup-go@v3
        with:
          go-version: v1.18

      - name: Set .exe extension for Windows
        run: echo "EXTENSION=.exe" >> $GITHUB_ENV
        if: matrix.target.os == 'windows'

      - name: Set executable filename
        run: echo "FILENAME=nyaa-${{ matrix.target.os }}-${{ matrix.target.arch }}${{ env.EXTENSION }}" >> $GITHUB_ENV

      - name: Build
        run: make OUTPUT=bin/${{ env.FILENAME }}
        env:
          GOOS: "${{ matrix.target.os }}"
          GOARCH: "${{ matrix.target.arch }}"

      - name: Compute checksums
        run: shasum --algorithm 256 bin/${{ env.FILENAME }} > bin/${{ env.FILENAME }}.sha256

      - uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: bin/${{ env.FILENAME }}
          tag: ${{ github.ref }}

      - uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: bin/${{ env.FILENAME }}.sha256
          tag: ${{ github.ref }}
